name: CI

on:
  push:
    branches:
    - master
  pull_request: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update stable
      - name: Check
        run: cargo check --all --all-features

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Install Rust
      run: rustup update stable
    - name: Test tiny
      run: cd demo; cargo run -- precomputed 10; cargo run --example str2id
    - name: Test small
      run: cd demo; cargo run -- precomputed 10 hash-only; cargo run --example str2id
    - name: Test medium
      run: cd demo; cargo run -- precomputed 1000; cargo run --example str2id
